// <auto-generated />
namespace CineChat.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class renew_models_verify : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(renew_models_verify));
        
        string IMigrationMetadata.Id
        {
            get { return "201511162132191_renew_models_verify"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
