// <auto-generated />
namespace CineChat.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class movie_poster : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(movie_poster));
        
        string IMigrationMetadata.Id
        {
            get { return "201511162151580_movie_poster"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
